### ISSUE TITLE
mainpage 동아리소개 추가

### ISSUE THREAD

**Issue by wwjdtm** [wwjdtm/jjinggeut#5]
mainpage 동아리소개 추가

**Comment by whismile** [comment]
Main 페이지에 들어가는 상단 컨텐츠인 Header를 업데이트 했습니다.
Footer 컨텐츠는 생각보다 정렬이 어려워 시간이 걸릴 것 같아 완성되는 대로 올리겠습니다.

**Comment by whismile** [comment]
Main 페이지에 들어가는 상단 컨텐츠인 Header를 업데이트 했습니다.
Footer 컨텐츠는 생각보다 정렬이 어려워 시간이 걸릴 것 같아 완성되는 대로 올리겠습니다.

+ Linux환경에서의 Jetbrain IDE .gitignore 파일을 추가해놓았습니다. Window를 쓰시거나 vscode IDE를 쓰시는 분들은 .gitignore에 설정파일을 무시하는 코드를 넣어주시길 바랍니다.
